Parse the returned response based on the set `accept_type` value
vmware/pyvcloud pull request #732
Opened 2020-12-09 20:56 UTC by mukultaneja

Adding a check of `accept_type` value before parsing
the returned response

Resolved: #731

Signed-off-by: mukultaneja <mtaneja@vmware.com>

2021-02-22 23:20 UTC, rocknes requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/732)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @mukultaneja)

___
*[pyvcloud/vcd/client.py, line 977 at r2](https://reviewable.io/reviews/vmware/pyvcloud/732#-MUB15FD3w4CmOQSkkuN:-MUB15FD3w4CmOQSkkuO:b-b4k8a0) ([raw file](https://github.com/vmware/pyvcloud/blob/20129d8dd725637bfb88b484ed6ea10744afb385/pyvcloud/vcd/client.py#L977)):*
> ```Python
>                 r = None
>                 try:
>                     if accept_type == 'application/json':
> ```

pyvcloud doesn't support `application/json` as Accept type.
Are you overriding the value of header from the pyvcloud client?

This change might look simple but has far reaching consequences. However, I don't see any issue for the time being.
___
*[pyvcloud/vcd/gateway.py, line 1164 at r2](https://reviewable.io/reviews/vmware/pyvcloud/732#-MUB1IRNAOF3atNvLVQY:-MUB1IRNAOF3atNvLVQZ:bpkeohj) ([raw file](https://github.com/vmware/pyvcloud/blob/20129d8dd725637bfb88b484ed6ea10744afb385/pyvcloud/vcd/gateway.py#L1164)):*
> ```Python
>             for static_route in static_routes_resource.staticRoutes.route:
>                 static_route_info = {}
>                 static_route_info['Network'] = str(static_route.network)
> ```

.text is the correct way to convert lxml objects to str.

e.g.
static_route.nextHop.text
int(static_route.mtu.text)


<!-- Sent from Reviewable.io -->

2021-02-22 23:20 UTC, rocknes reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/732)* status: all files reviewed, 2 unresolved discussions (waiting on @mukultaneja)



<!-- Sent from Reviewable.io -->

2021-02-26 11:10 UTC, mukultaneja reviewed
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/732)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @rocknes)

___
*[pyvcloud/vcd/client.py, line 977 at r2](https://reviewable.io/reviews/vmware/pyvcloud/732#-MUB15FD3w4CmOQSkkuN:-MUT0qL0CHKf5AYnpu2o:bs7wumb) ([raw file](https://github.com/vmware/pyvcloud/blob/20129d8dd725637bfb88b484ed6ea10744afb385/pyvcloud/vcd/client.py#L977)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

pyvcloud doesn't support `application/json` as Accept type.
Are you overriding the value of header from the pyvcloud client?

This change might look simple but has far reaching consequences. However, I don't see any issue for the time being.


</blockquote></details>

Done.
___
*[pyvcloud/vcd/gateway.py, line 1164 at r2](https://reviewable.io/reviews/vmware/pyvcloud/732#-MUB1IRNAOF3atNvLVQY:-MUT0yov3aOFuizOleed:b-896fix) ([raw file](https://github.com/vmware/pyvcloud/blob/20129d8dd725637bfb88b484ed6ea10744afb385/pyvcloud/vcd/gateway.py#L1164)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

.text is the correct way to convert lxml objects to str.

e.g.
static_route.nextHop.text
int(static_route.mtu.text)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-03 08:47 UTC, rocknes reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vmware/pyvcloud/732#-:-MUrGJTS2xiMrlUU4TRd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @rocknes)



<!-- Sent from Reviewable.io -->

2021-03-03 08:48 UTC, merged